[package]
name = "vox_machina"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
byteorder = "0.5.0"
nalgebra = "0.5.1"

[dev-dependencies]
quickcheck = "0.2"

[lib]
name = "carved_rust"
crate-type = ["dylib"]
