[package]
name = "vox_machina"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
byteorder = "0.5.0"
nalgebra = "0.5.1"
gfx = "*"
glutin = "*"
gfx_window_glutin = "*"

[dev-dependencies]
quickcheck = "0.2"

[[bin]]
name = "vox_machina"
path = "src/main.rs"
