[package]
name = "carved_rust"
version = "0.1.0"
authors = ["David McGillicuddy <dmcgill9071@gmail.com>"]

[dependencies]
byteorder = "0.5.0"
nalgebra = "0.5.1"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"

[lib]
name = "carved_rust"
crate-type = ["dylib"]
